config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'spots/new', to: 'spots#new'
  post 'spots', to: 'spots#create'
  delete 'spots/:id', to: 'spots#destroy'
  resources :spots, only: [:destroy, :show, :edit, :update]
  resources :users, only: [:index, :show, :new, :create, :likes, :edit, :update] do
    member do
      get :likes
    end
  end  
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :spot
end

app/models/spot.rb
class Spot < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 40 }
  validates :about, presence: true, length: { maximum: 255 }
  belongs_to :user
  has_many :favorites, foreign_key: 'spot_id', dependent: :destroy
  has_many :users, through: :favorites
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :introduce, length: { maximum: 255 }
  has_many :spots
  has_many :favorites
  has_many :subspots, through: :favorites, source: :spot
  mount_uploader :image, ImageUploader
  
  def favorite(spot)
    favorites.find_or_create_by(spot_id: spot.id)
  end
  
  def unfavorite(spot)
   favorite = favorites.find_by(spot_id: spot.id)
   favorite.destroy if favorite
  end
  
  def favorite?(spot)
   spot.favorites.where(user_id: id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_spots = user.spots.count
    @count_favorites = user.favorites.count
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    spot = Spot.find(params[:spot_id])
    current_user.favorite(spot)
    flash[:success] = '投稿をお気に入りしました。'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    spot = Spot.find(params[:spot_id])
    current_user.unfavorite(spot)
    flash[:success] = '投稿のお気に入りを解除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :edit]
  
  def new
    @spot = current_user.spots.new
  end
  
  def show
    @spot = Spot.find(params[:id])
  end
  
  def destroy
    @spot.destroy
    flash[:success] = 'スポットを削除しました !'
    redirect_to controller: 'users', action: 'show', id: current_user
  end
  
  def create
    @spot = current_user.spots.build(spot_params)

    if @spot.save
      flash[:success] = 'スポットを投稿しました !'
      redirect_to controller: 'users', action: 'show', id: current_user
    else
      flash.now[:danger] = 'スポットの投稿に失敗しました !'
      render :new
    end
  end
  
  def edit
    @spot = Spot.find(params[:id])
  end
  
  def update
    @spot = Spot.find(params[:id])
    @spot.update(spot_params)
    
    if @spot.save
      flash[:success] = '投稿内容を更新しました !'
      redirect_to @spot
    else
      flash[:danger] = '投稿内容の更新に失敗しました !'
      render :edit
    end
  end

  private
  
  def spot_params
    params.require(:spot).permit(:name, :address, :about, :picture, :remove_picture)
  end
  
  def correct_user
    @spot = current_user.spots.find_by(id: params[:id])
    unless @spot
      redirect_to root_url
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @user = User.new
    if logged_in? 
      redirect_back(fallback_location: user_path(current_user)) 
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :require_user_logged_in, only: [:index, :show, :likes, :edit, :update]
   before_action :correct_user, only: [:edit, :update]
   
  def index
    @users = User.order(id: :desc).page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
    @spots = @user.spots.order(id: :desc).page(params[:page]).per(15)
    counts(@user)
  end

  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def likes
    @user = User.find(params[:id])
    @subspots = @user.subspots.order(id: :desc).page(params[:page]).per(15)
    counts(@user)
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save(context: :user_update)
      flash[:success] = 'ユーザー情報を編集しました !'
      redirect_to controller: 'users', action: 'show', id: current_user
    else
      flash.now[:danger] = 'ユーザー情報の編集に失敗しました !'
      render "users/edit"
    end   
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました !'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました !'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduce, :image, :remove_image)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/favorites/_favorite.html.erb
<% unless current_user == spot %>
  <% if current_user.favorite?(spot) %>
    <%= form_with(model: current_user.favorites.find_by(spot_id: spot.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :spot_id, spot.id %>
    <%= f.submit 'お気に入り解除', class: 'btn btn-danger btn-sm btn-favorite' %>
  <% end %>

  <% else %>
    <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
    <%= hidden_field_tag :spot_id, spot.id %>
    <%= f.submit 'お気に入り登録', class: 'btn btn-primary btn-sm btn-favorite' %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="feedout alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <% if logged_in? %>
      <%= link_to 'My Spot', user_path(current_user), class: "navbar-brand" %>
    <% else %>
      <%= link_to 'My Spot', root_path, class: "navbar-brand" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'ユーザ一覧', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'マイページ', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'ユーザ登録', root_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>  
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Spot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>


  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/spots/_spots.html.erb
<ul class="list-unstyled">
  <% spots.each do |spot| %>
    <li class="media mb-3">
      <div class="show">
        <%= link_to spot.user.name, user_path(spot.user) %> <span class="text-muted">posted at <%= spot.created_at.in_time_zone('Tokyo') %></span>
        <div class="show-menu">
            <% if spot.picture? %>
              <%= image_tag spot.picture.url(:thumb100), class: 'image' %>
            <% else %>
              <%= image_tag"l_e_others_501.png", size: '284x179', class: 'image' %>
            <% end %>
          <div class="side">
            <table class="mt-3">
              <tr>
                <th>スポット名</th>
                <td><%= truncate(spot.name, omission: '...', length: 18) %></td>
              </tr>
              <tr>
                <th>住所</th>
                <td><%= truncate(spot.address, omission: '...', length: 18) %></td>
              </tr>
            </table>
            <ul class="pt-4">
              <% if current_user == spot.user %>
                <li><%= link_to '詳細を見る', spot, id: spot.id %></li>
                <li><%= link_to '編集する', edit_spot_path(spot) %></li>
                <li><%= link_to "この投稿を削除する", spot, method: :delete, data: { confirm: "You sure?" } %></li>
              <% else %>
                 <li class="pt-4"><%= link_to '詳細を見る', spot, id: spot.id %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </li>
  <% end %>
  <div class="spots-paginate">
    <%= paginate spots %>
  </div>
</ul>

app/views/spots/edit.html.erb
<div class="row mb-5">
  <div class="col-lg-6 offset-lg-3 col-sm-8 offset-sm-2">
    <%= form_with(model: @spot, local: true) do |f| %>
      <% if @spot.errors.any? %>
        <%= render 'layouts/error_messages', model: f.object %>
      <% end %>
  　　
      <div class="form-group">
        <%= f.label :name, 'スポット名称' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :picture, 'スポット写真' %>
        <p><%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %></p>
        <p><%= f.check_box :remove_picture %>画像を設定しない</p>
      </div>
    
      <div class="form-group">
        <%= f.label :address, '住所' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>
      
      <div>
        <%= f.label :about, 'このスポットについての説明' %>
        <%= f.text_area :about, size: "20x10", class: 'form-control' %>
        <%= f.submit 'スポット情報を更新する', class: 'btn btn-primary mt-5 btn-edit' %>
      </div>   
    <% end %>
  </div>
</div>

app/views/spots/new.html.erb
<div class="row mb-4">
  <div class="col-lg-6 offset-lg-3 col-sm-8 offset-sm-2">
    <%= form_with(model: @spot, local: true, html: { multipart: true }) do |f| %>
    　<% if @spot.errors.any? %>
    　   <%= render 'layouts/error_messages', model: f.object %>
  　　<% end %>
  　　
      <div class="form-group">
        <%= f.label :name, 'スポット名称' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :picture, 'スポット写真' %>
        <p><%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %></p>
      </div>
    
      <div class="form-group">
        <%= f.label :address, '住所' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>
      
      <div>
        <%= f.label :about, 'このスポットについての説明' %>
        <%= f.text_area :about, placeholder: 'このスポットの良いところなど自由に記入しましょう！', size: "20x10", class: 'form-control' %>
        <%= f.submit '投稿する', class: 'btn btn-primary mt-5' %>
      </div>   
    <% end %>
  </div>
</div>

app/views/spots/show.html.erb
<div class="content">
  <div class="main">
    <h3><%= link_to @spot.user.name, user_path(@spot.user) %>さんの投稿</h3>
    <% if @spot.picture? %>
      <%= image_tag @spot.picture.url(:thumb), class: 'image' %>
    <% else %>
      <%= image_tag"l_e_others_501.png", size: '500x300', class: 'image' %>
    <% end %>
  </div>
  <div class="description">
    <table>
      <tr>
        <th>スポット名</th>
        <td><%= @spot.name %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><span><%= @spot.address %></span></td>
      </tr>
        <th>スポットの説明</th>
        <td><span><%= simple_format(@spot.about) %></span></td>
      </tr>
    </table>
  </div>
  <div class="foot">
    <%= render "favorites/favorite", spot: @spot %>
  </div>
</div>    

app/views/toppages/index.html.erb
<div class="main-content mt-5">
  <div class="topimage">
    <h1 class="heading">My Spotへようこそ</h1>
    <div class="wrapper">
      <p class="txt">
        ・家だと作業に集中できない・・・<br>
        ・気分転換に屋外で作業したいけど良い場所がわからない・・・<br>
        このような悩みを持つ方がいるのではないでしょうか？？<br>
        ここでは、それぞれのユーザのお気に入りのスポットを共有できます。<br>
        まずは、あなたのおすすめスポットを投稿してみましょう！
      </p>
    </div>
  </div>
  <div class="pt-5">
    <%= render 'users/new' %>
  </div>
</div>

app/views/users/_new.html.erb
<div class="text-center">
  <h2>ユーザ登録</h2>
</div>

<div class="row mb-4 pt-4">
  <div class="col-lg-4 offset-lg-4 col-sm-8 offset-sm-2">
    <%= form_with(model: @user, local: true) do |f| %>
      <% if @user.errors.any? %>
      　  <%= render 'layouts/error_messages', model: f.object %>
    　<% end %>
      
      <div class="form-group">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, placeholder: '※１０文字以内', class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（確認）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
  
      <%= f.submit '登録', class: 'btn btn-primary btn-block mt-2' %>
    <% end %>
    <p><%= link_to 'ユーザー登録済の方はこちら', login_path %></p>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-lg-6 offset-lg-3 col-sm-8 offset-sm-2 mt-5">
    <%= form_with(model: @user, local: true) do |f| %>
      <% if @user.errors.any? %>
        <%= render 'layouts/error_messages', model: f.object %>
      <% end %>
    　　
      <div class="form-group">
        <%= f.label :image, 'プロフィール写真' %>
        <p><%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %></p>
        <p><%= f.check_box :remove_image %>画像を設定しない</p>
      </div>
      
      <div class="form-group">
        <%= f.label :name, 'ユーザ名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :introduce, '自己紹介（255文字以内）' %>
        <%= f.text_area :introduce, :maxlength => "255", :size => "80x7",  class: 'form-control'  %>
      </div>
      <%= f.submit 'プロフィール編集を完了する', class: 'btn btn-primary mb-3 btn-edit' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="list">
  <% if @users.any? %>
    <% @users.each do |user| %>
      <div class="unit">
        <% if user.image?%>
          <%= image_tag user.image.url(:thumb100), class: 'rounded-circle image' %>
        <% else %>
          <%= image_tag"noimage.png", size: '100x100', class: 'rounded-circle image' %>
        <% end %>
        <h3 class="pl-4 pt-3"><%= link_to user.name, user_path(user) %></h3>
      </div>
    <% end %>
  <% end %>
</div>
<div class="users-paginate">
  <%= paginate @users, class: 'paginate' %>
</div>

app/views/users/likes.html.erb
<div class="home">
  <div class="sidebar">
    <div class="item">
      <% if current_user == @user %>
        <% if @user.image? %>
          <%= image_tag @user.image.url(:thumb170), class: 'avatar rounded-circle image mt-5' %>
          <h3 class="pb-2"><%= @user.name %></h3>
          <div class="user-menu">
            <p><%= simple_format(@user.introduce) %></p>
          </div>
        <% else %>
          <%= image_tag"noimage.png", size: '170x170', class: 'avatar rounded-circle image mt-5' %>
          <h3 class="pb-2"><%= @user.name %></h3>
          <div class="user-menu">
            <p><%= simple_format(@user.introduce) %></p>
          </div>
        <% end %>
      <% else %>
        <% if @user.image? %>
          <%= image_tag @user.image.url(:thumb170), class: 'avatar rounded-circle image mt-5' %>
          <h3 class="pb-2"><%= @user.name %></h3>
          <div class="user-menu">
            <p><%= simple_format(@user.introduce) %></p>
          </div>
        <% else %>
          <%= image_tag"noimage.png", size: '170x170', class: 'avatar rounded-circle image mt-5' %>
          <h3 class="pb-2"><%= @user.name %></h3>
        <% end %>
      <% end %>
      <% if current_user == @user %>
        <p><%= link_to 'プロフィールを編集する', edit_user_path(@user) %></p>
        <p><%= link_to '投稿する', spots_new_path, class: 'btn btn-primary w-75' %></p>
      <% end %>
    </div>
  </div>
  <div class="feature pt-5">
    <div class="tab">
      <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿一覧  <span class="badge badge-secondary ml-1 pt-1"><%= @count_spots %></span></a></li>
        <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り<span class="badge badge-secondary ml-1 pt-1"><%= @count_favorites %></span></a></li>
      </ul>
      <%= render 'spots/spots', spots: @subspots %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="contents">
  <%= render 'users/new' %>
</div>

app/views/users/show.html.erb
<div class="home">
  <div class="sidebar">
    <div class="item">
      <div class="user-image">
        <% if current_user == @user %>
          <% if @user.image? %>
            <%= image_tag @user.image.url(:thumb170), class: 'avatar rounded-circle image mt-5' %>
            <h3 class="pb-2"><%= @user.name %></h3>
            <div class="user-menu">
              <p><%= simple_format(@user.introduce) %></p>
            </div>
          <% else %>
            <%= image_tag"noimage.png", size: '170x170', class: 'avatar rounded-circle image mt-5' %>
            <h3 class="pb-2"><%= @user.name %></h3>
            <div class="user-menu">
              <p><%= simple_format(@user.introduce) %></p>
            </div>
          <% end %>
        <% else %>
          <% if @user.image? %>
            <%= image_tag @user.image.url(:thumb170), class: 'avatar rounded-circle image mt-5' %>
            <h3 class="pb-2"><%= @user.name %></h3>
            <div class="user-menu">
              <p><%= simple_format(@user.introduce) %></p>
            </div>
          <% else %>
            <%= image_tag"noimage.png", size: '170x170', class: 'avatar rounded-circle image mt-5' %>
            <h3 class="pb-2"><%= @user.name %></h3>
          <% end %>
        <% end %>
      </div>
      <div class="post">
        <% if current_user == @user %>
          <p><%= link_to 'プロフィールを編集する', edit_user_path(@user) %></p>
          <p><%= link_to '投稿する', spots_new_path, class: 'btn btn-primary w-75' %></p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="feature pt-5">
    <div class="tab">
      <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿一覧  <span class="badge badge-secondary ml-1 pt-1"><%= @count_spots %></span></a></li>
        <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り<span class="badge badge-secondary ml-1 pt-1"><%= @count_favorites %></span></a></li>
      </ul>
      <%= render 'spots/spots', spots: @spots %>
    </div>
  </div>
</div>